set nocompatible
set number
set relativenumber
set tabstop=4
set shiftwidth=4
set expandtab
syntax on

call plug#begin('~/.vim/plugged')
Plug 'morhetz/gruvbox'
Plug 'vim-airline/vim-airline'
Plug 'preservim/nerdtree'
Plug 'github/copilot.vim'
Plug 'tpope/vim-commentary'
Plug 'dense-analysis/ale'
call plug#end()

let g:NERDTreeShowHidden=1
colorscheme gruvbox
set background=dark
